# SPDX-FileCopyrightText: 2026 AlgorIT Software Consultancy
# SPDX-License-Identifier: BSL-1.0

add_executable(sqlixx.unittest)
set_target_properties(sqlixx.unittest PROPERTIES CXX_MODULE_STD ON)
target_sources(
    sqlixx.unittest
    PRIVATE
        sqlite_mock.cpp
        error_test.cpp
        error.sqlite_test.cpp
        connection_test.cpp
        connection.open_test.cpp
        bind_context_test.cpp
        binders_test.cpp
        statement_test.cpp
        #statement.coro_test.cpp
        statement.prepare_test.cpp
        #statement.read_test.cpp
        #statement.step_test.cpp
        statement.bind_test.cpp
)
target_link_libraries(
    sqlixx.unittest
    PRIVATE
        sqlixx::sqlixx
        Catch2::Catch2WithMain
        trompeloeil
        $<$<CXX_COMPILER_ID:GNU>:-lstdc++exp>
)
target_link_options(
    sqlixx.unittest
    PRIVATE
        "LINKER:--wrap=sqlite3_errstr"
        "LINKER:--wrap=sqlite3_errmsg"
        "LINKER:--wrap=sqlite3_extended_errcode"
        "LINKER:--wrap=sqlite3_open_v2"
        "LINKER:--wrap=sqlite3_close_v2"
        "LINKER:--wrap=sqlite3_prepare_v3"
        "LINKER:--wrap=sqlite3_finalize"
        "LINKER:--wrap=sqlite3_step"
        "LINKER:--wrap=sqlite3_reset"
        "LINKER:--wrap=sqlite3_clear_bindings"
        "LINKER:--wrap=sqlite3_bind_int"
        "LINKER:--wrap=sqlite3_bind_int64"
        "LINKER:--wrap=sqlite3_bind_double"
        "LINKER:--wrap=sqlite3_bind_text"
        "LINKER:--wrap=sqlite3_bind_blob64"
        "LINKER:--wrap=sqlite3_bind_zeroblob64"
        "LINKER:--wrap=sqlite3_bind_null"
        "LINKER:--wrap=sqlite3_bind_parameter_count"
        "LINKER:--wrap=sqlite3_bind_parameter_index"
        "LINKER:--wrap=sqlite3_data_count"
        "LINKER:--wrap=sqlite3_column_int64"
        "LINKER:--wrap=sqlite3_column_double"
        "LINKER:--wrap=sqlite3_column_text"
        "LINKER:--wrap=sqlite3_column_blob"
        "LINKER:--wrap=sqlite3_column_bytes"
)
target_enable_coverage(sqlixx.unittest)
target_enable_sanitizer(sqlixx.unittest)
catch_discover_tests(sqlixx.unittest DISCOVERY_MODE PRE_TEST)
