# SPDX-FileCopyrightText: 2026 AlgorIT Software Consultancy
# SPDX-License-Identifier: BSL-1.0

FROM ghcr.io/bemanproject/infra-containers-clang:latest
RUN useradd -m -s /bin/bash developer
USER developer
